# Form implementation generated from reading ui file 'linux-warn.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 135)
        Form.setMinimumSize(QtCore.QSize(465, 135))
        Form.setMaximumSize(QtCore.QSize(465, 135))
        self.infoText = QtWidgets.QLabel(parent=Form)
        self.infoText.setGeometry(QtCore.QRect(10, -10, 461, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoText.sizePolicy().hasHeightForWidth())
        self.infoText.setSizePolicy(sizePolicy)
        self.infoText.setMinimumSize(QtCore.QSize(0, 100))
        self.infoText.setStyleSheet("font: 700 28pt \"Cantarell\";\n"
"")
        self.infoText.setWordWrap(True)
        self.infoText.setObjectName("infoText")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Form)
        self.buttonBox.setGeometry(QtCore.QRect(110, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Don\'t Die Message"))
        self.infoText.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">You are running Don\'t Die with sudo. As a result, your window theme may not work. If you want your theme, and running the shutdown command on your system works without sudo, you can run Don\'t Die without sudo.</span></p></body></html>"))
